### ISSUE TITLE
Unit tests using Quick and Nimble

### ISSUE THREAD

**Issue by wailaw** [devxoul/Drrrible#1]
I've read all your sample projects built with your RxMVVM architecture. I really love it. It's the most practical MVVM architecture in my opinion. 

The sample projects are great. They've demo almost all situations in using RxSwift with MVVM. 

 I would now like to start my new projects with BDD and RxMVVM. However, I'm not sure what's the best way to write the tests in this case. 

It'll be really appreciated if you can add some tests in BDD style in your sample projects.

Thanks for all the works!

**Comment by devxoul** [comment]
@wailaw, thank for your interesting! I'm planning to write tests using [RxExpect](https://github.com/devxoul/RxExpect) which makes it easy to test Observables. You can check [RxTodo Tests](https://github.com/devxoul/RxTodo/tree/master/RxTodoTests/Sources/Tests) to see how RxExpect looks like.

**Comment by wailaw** [comment]
@devxoul Thanks for the suggestion! I've just gone through it. Is it possible to use RxExpect with Quick?

**Comment by devxoul** [comment]
I haven't used like that but I think it's possible if you're using Quick for just defining behaviors and using RxExpect for assertion.

**Comment by devxoul** [comment]
@wailaw, I've added some test code: https://github.com/devxoul/Drrrible/tree/master/DrrribleTests/Sources

**Comment by wailaw** [comment]
@devxoul Sorry for the late reply. Thanks so much! I'll check it and compare with my current code.
