### ISSUE TITLE
HI,i get some issus when I pod install 

### ISSUE THREAD

**Issue by sjsurf** [devxoul/Drrrible#10]
![screen shot 2017-10-10 at 10 52 41 am](https://user-images.githubusercontent.com/20354232/31367318-2a49920a-ada9-11e7-829e-96addfc25bea.png)
how can I solve it?

**Comment by devxoul** [comment]
@sjsurf, please try again with the latest `master` branch. There are some updates :)

**Comment by sjsurf** [comment]
Thanks,when i install pods form latest master get error too,but solve by use pod update.thank u very much.
