### ISSUE TITLE
Curious about statusBarStyle

### ISSUE THREAD

**Issue by asyl** [devxoul/Drrrible#7]
I really like your code & craft. I learnt a lot from your awesome works.

I've got stuck with thoughts about `statusBarStyle` in your app. I reviewed all the code in Drrrible. Unfortunately, I couldn't realize how you change the `statusBarStyle` between `SplashViewController` & `MainTabBarController`.
Definitely, there is the answer that I couldn't discover. Looking forward to your reply.

Thank you!

**Comment by devxoul** [comment]
I set UINavigationBar's `barStyle` to `.black`. It automatically adjusts status bar style. You may check [this line](https://github.com/devxoul/Drrrible/blob/1278010e4ec2e40f93daedd01e7770c28b84ee9f/Drrrible/Sources/AppDelegate.swift#L101) :)

**Comment by asyl** [comment]
@devxoul thank you for your reply!
